import type { ToolCandidate } from "../types";

/** Curated mock stream — swap for RSS/GitHub providers later */
export function getMockCandidates(): ToolCandidate[] {
  const e = (
    kind: ToolCandidate["evidence"][0]["kind"],
    label: string,
    source: string,
    weight: number,
  ) => ({ kind, label, source, weight });

  return [
    {
      id: "cursor",
      name: "Cursor",
      tagline: "IDE with inline agents and repo-wide edits.",
      url: "https://cursor.com",
      tags: ["ui", "tsx", "next", "productivity"],
      lastActivityDays: 3,
      stars: 0,
      forks: 0,
      mentionCount: 14,
      maintainerHealth: 0.95,
      evidence: [
        e("social", "Repeated mentions in dev Twitter / Bluesky threads", "social", 0.9),
        e("article", "Independent reviews vs Copilot", "tech blogs", 0.75),
      ],
    },
    {
      id: "continue",
      name: "Continue",
      tagline: "Open-source autopilot for VS Code / JetBrains.",
      url: "https://continue.dev",
      repoUrl: "https://github.com/continuedev/continue",
      tags: ["ui", "typescript", "server", "productivity"],
      lastActivityDays: 5,
      stars: 28000,
      forks: 2400,
      mentionCount: 11,
      maintainerHealth: 0.92,
      evidence: [
        e("repo", "Active contributors & frequent releases", "GitHub", 0.95),
        e("package", "VS Code marketplace installs", "marketplace", 0.85),
      ],
    },
    {
      id: "vercel-ai-sdk",
      name: "Vercel AI SDK",
      tagline: "TypeScript helpers for streaming LLM UI and tools.",
      url: "https://sdk.vercel.ai",
      repoUrl: "https://github.com/vercel/ai",
      tags: ["tsx", "react", "server", "api", "typescript"],
      lastActivityDays: 7,
      stars: 12000,
      forks: 1100,
      mentionCount: 18,
      maintainerHealth: 0.94,
      evidence: [
        e("repo", "High velocity + large ecosystem", "GitHub", 0.9),
        e("article", "Framework guides (Next.js)", "Vercel / community", 0.8),
      ],
    },
    {
      id: "langgraph",
      name: "LangGraph",
      tagline: "Stateful multi-agent workflows on top of LangChain.",
      url: "https://langchain-ai.github.io/langgraph/",
      repoUrl: "https://github.com/langchain-ai/langgraph",
      tags: ["python", "server", "api", "graphql"],
      lastActivityDays: 6,
      stars: 11000,
      forks: 900,
      mentionCount: 15,
      maintainerHealth: 0.9,
      evidence: [
        e("repo", "LangChain org maintenance", "GitHub", 0.88),
        e("article", "Agent design patterns", "HN / blogs", 0.72),
      ],
    },
    {
      id: "ollama",
      name: "Ollama",
      tagline: "Local LLM runner with simple CLI and API.",
      url: "https://ollama.com",
      repoUrl: "https://github.com/ollama/ollama",
      tags: ["server", "rust", "docker", "api"],
      lastActivityDays: 4,
      stars: 132000,
      forks: 9200,
      mentionCount: 22,
      maintainerHealth: 0.93,
      evidence: [
        e("repo", "Very high star velocity", "GitHub", 0.95),
        e("social", "Local-first movement", "community", 0.7),
      ],
    },
    {
      id: "litellm",
      name: "LiteLLM",
      tagline: "Unified OpenAI-compatible router across providers.",
      url: "https://github.com/BerriAI/litellm",
      repoUrl: "https://github.com/BerriAI/litellm",
      tags: ["python", "api", "server", "serverless", "aws"],
      lastActivityDays: 2,
      stars: 19000,
      forks: 2600,
      mentionCount: 16,
      maintainerHealth: 0.88,
      evidence: [
        e("repo", "Frequent releases", "GitHub", 0.9),
        e("package", "PyPI adoption", "pypi", 0.75),
      ],
    },
    {
      id: "temporal",
      name: "Temporal",
      tagline: "Durable workflows with replay — good for agent tasks.",
      url: "https://temporal.io",
      repoUrl: "https://github.com/temporalio/temporal",
      tags: ["go", "server", "kubernetes", "pipeline", "deploy"],
      lastActivityDays: 10,
      stars: 11000,
      forks: 950,
      mentionCount: 9,
      maintainerHealth: 0.91,
      evidence: [
        e("repo", "Enterprise traction", "GitHub", 0.85),
        e("article", "Workflow vs queue essays", "blogs", 0.65),
      ],
    },
    {
      id: "dagger",
      name: "Dagger",
      tagline: "Programmable CI pipelines in code (not YAML spaghetti).",
      url: "https://dagger.io",
      tags: ["docker", "ci", "cd", "pipeline", "go"],
      lastActivityDays: 14,
      stars: 11000,
      forks: 700,
      mentionCount: 8,
      maintainerHealth: 0.87,
      evidence: [
        e("repo", "Consistent ship cadence", "GitHub", 0.82),
        e("social", "DevOps circles", "social", 0.6),
      ],
    },
    {
      id: "pulumi",
      name: "Pulumi",
      tagline: "Infrastructure as code in TS/Python/Go.",
      url: "https://pulumi.com",
      tags: ["terraform", "aws", "azure", "gcp", "deploy"],
      lastActivityDays: 12,
      stars: 22000,
      forks: 900,
      mentionCount: 10,
      maintainerHealth: 0.89,
      evidence: [
        e("repo", "Multi-cloud examples", "GitHub", 0.8),
        e("article", "vs Terraform comparisons", "blogs", 0.68),
      ],
    },
    {
      id: "modal",
      name: "Modal",
      tagline: "Serverless Python/GPU without owning k8s.",
      url: "https://modal.com",
      tags: ["python", "serverless", "lambda", "gpu", "pipeline"],
      lastActivityDays: 8,
      stars: 7000,
      forks: 450,
      mentionCount: 12,
      maintainerHealth: 0.9,
      evidence: [
        e("article", "ML inference posts", "blogs", 0.78),
        e("social", "ML Twitter", "social", 0.65),
      ],
    },
    {
      id: "braintrust",
      name: "Braintrust",
      tagline: "Evals, datasets, and logging for LLM apps.",
      url: "https://braintrust.dev",
      tags: ["typescript", "python", "api", "server"],
      lastActivityDays: 9,
      stars: 900,
      forks: 80,
      mentionCount: 7,
      maintainerHealth: 0.84,
      evidence: [
        e("repo", "Docs + SDK churn", "GitHub", 0.75),
        e("article", "Eval tooling comparisons", "blogs", 0.62),
      ],
    },
    {
      id: "openrouter",
      name: "OpenRouter",
      tagline: "Single API for many models — routing and keys.",
      url: "https://openrouter.ai",
      tags: ["api", "serverless", "typescript"],
      lastActivityDays: 1,
      stars: 0,
      forks: 0,
      mentionCount: 13,
      maintainerHealth: 0.92,
      evidence: [
        e("social", "Default for hobby routing", "community", 0.88),
        e("package", "SDK mentions", "npm/pypi", 0.55),
      ],
    },
    {
      id: "crewai",
      name: "CrewAI",
      tagline: "Role-based multi-agent crews in Python.",
      url: "https://crewai.com",
      repoUrl: "https://github.com/crewAIInc/crewAI",
      tags: ["python", "server", "api"],
      lastActivityDays: 11,
      stars: 28000,
      forks: 3800,
      mentionCount: 14,
      maintainerHealth: 0.86,
      evidence: [
        e("repo", "Fast star growth", "GitHub", 0.87),
        e("article", "Agent framework shootouts", "blogs", 0.7),
      ],
    },
    {
      id: "semantic-kernel",
      name: "Semantic Kernel",
      tagline: "Microsoft SDK for orchestration + plugins (.NET/py/Java).",
      url: "https://github.com/microsoft/semantic-kernel",
      repoUrl: "https://github.com/microsoft/semantic-kernel",
      tags: ["server", "api", "azure", "dotnet"],
      lastActivityDays: 6,
      stars: 24000,
      forks: 3400,
      mentionCount: 10,
      maintainerHealth: 0.93,
      evidence: [
        e("repo", "MS-backed releases", "GitHub", 0.9),
        e("article", "Enterprise walkthroughs", "MS docs", 0.72),
      ],
    },
    {
      id: "cohere-toolkit",
      name: "Cohere Toolkit",
      tagline: "RAG / chat starter kits from Cohere ecosystem.",
      url: "https://github.com/cohere-ai/cohere-toolkit",
      repoUrl: "https://github.com/cohere-ai/cohere-toolkit",
      tags: ["python", "api", "server", "react"],
      lastActivityDays: 20,
      stars: 800,
      forks: 120,
      mentionCount: 5,
      maintainerHealth: 0.78,
      evidence: [
        e("repo", "Tighter niche", "GitHub", 0.65),
        e("article", "Vendor guides", "docs", 0.55),
      ],
    },
    {
      id: "ray-serve-llm",
      name: "Ray Serve (LLM patterns)",
      tagline: "Scale Python inference behind a production router.",
      url: "https://docs.ray.io/en/latest/serve/index.html",
      tags: ["python", "kubernetes", "server", "gpu", "pipeline"],
      lastActivityDays: 18,
      stars: 36000,
      forks: 4800,
      mentionCount: 8,
      maintainerHealth: 0.9,
      evidence: [
        e("repo", "Anyscale maintenance", "GitHub", 0.88),
        e("article", "Large-scale ML ops", "blogs", 0.7),
      ],
    },
    {
      id: "hf-transformers",
      name: "Hugging Face Transformers",
      tagline: "De facto library for model weights + inference hooks.",
      url: "https://huggingface.co/docs/transformers",
      repoUrl: "https://github.com/huggingface/transformers",
      tags: ["python", "gpu", "server", "api"],
      lastActivityDays: 3,
      stars: 150000,
      forks: 38000,
      mentionCount: 25,
      maintainerHealth: 0.96,
      evidence: [
        e("repo", "Dominant ecosystem", "GitHub", 0.98),
        e("package", "pip / conda ubiquity", "pypi", 0.95),
      ],
    },
    {
      id: "chromadb",
      name: "Chroma",
      tagline: "Embeddings DB for local or server RAG.",
      url: "https://trychroma.com",
      repoUrl: "https://github.com/chroma-core/chroma",
      tags: ["python", "server", "api", "database", "rust"],
      lastActivityDays: 9,
      stars: 19000,
      forks: 1600,
      mentionCount: 17,
      maintainerHealth: 0.88,
      evidence: [
        e("repo", "RAG default choice for many", "GitHub", 0.9),
        e("social", "Tutorial spam but real usage", "community", 0.66),
      ],
    },
    {
      id: "milvus",
      name: "Milvus",
      tagline: "Vector database for large-scale search.",
      url: "https://milvus.io",
      repoUrl: "https://github.com/milvus-io/milvus",
      tags: ["kubernetes", "database", "server", "gpu", "aws"],
      lastActivityDays: 15,
      stars: 36000,
      forks: 4300,
      mentionCount: 11,
      maintainerHealth: 0.89,
      evidence: [
        e("repo", "CNCF-adjacent adoption", "GitHub", 0.85),
        e("article", "Benchmark posts", "blogs", 0.64),
      ],
    },
    {
      id: "playwright-mcp",
      name: "Playwright MCP",
      tagline: "Browser automation exposed as MCP tools for agents.",
      url: "https://github.com/microsoft/playwright-mcp",
      repoUrl: "https://github.com/microsoft/playwright-mcp",
      tags: ["typescript", "browser", "ui", "server"],
      lastActivityDays: 7,
      stars: 12000,
      forks: 900,
      mentionCount: 12,
      maintainerHealth: 0.91,
      evidence: [
        e("repo", "MS + Playwright synergy", "GitHub", 0.88),
        e("article", "Agent+browser posts", "blogs", 0.74),
      ],
    },
    {
      id: "anthropic-sdk",
      name: "Anthropic SDK",
      tagline: "Official SDK for Claude APIs.",
      url: "https://docs.anthropic.com",
      tags: ["typescript", "python", "api", "server"],
      lastActivityDays: 4,
      stars: 0,
      forks: 0,
      mentionCount: 19,
      maintainerHealth: 0.94,
      evidence: [
        e("package", "SDK references everywhere", "npm/pypi", 0.9),
        e("article", "Vendor docs / courses", "docs", 0.8),
      ],
    },
  ];
}
